### ISSUE TITLE
Constant and periodic CPU load

### ISSUE THREAD

**Issue by dontevenblink** [linuxserver/Heimdall#487] opened 2020-07-04 03:51 UTC
Heimdall is exhibiting unusual and periodic CPU load on my system. 

In the first image the chart starts with one instance of Heimdall open in FireFox. There, about once per second, are pretty substantial periodic CPU spikes. You can see where I close the window and the CPU usage goes flat in the middle. The big spike is when I opened the window again, and the periodic load returns after I clicked on one the the dashboard links.

![Screen Shot 2020-07-03 at 11 25 16 PM](https://user-images.githubusercontent.com/21349125/86504467-9cabe600-bd86-11ea-8cce-2cb55ca8543b.png)

It carries on like that in perpetuity as far as I can tell.

![Screen Shot 2020-07-03 at 11 29 27 PM](https://user-images.githubusercontent.com/21349125/86504534-818da600-bd87-11ea-89f9-6b672088f55e.png)

The only processes showing much load during this time, I think, are php-fpm.

![Screen Shot 2020-07-03 at 11 29 51 PM](https://user-images.githubusercontent.com/21349125/86504559-ad109080-bd87-11ea-9d09-bdd88d45ad9c.png)

I've got 10 containers running on this box and while this is happening, Heimdall is loading the CPU more than any other container, including an instance of Jellyfin actively streaming 1080p video. What is this process doing? I'm guessing this isn't expected behavior. Anecdotally, a friend of mine is observing the same of his heimdall instance. There was an issue that looked similar a while back, but it appeared to be closed without any resolution.

**Comment by jes1417** [comment] 2020-07-20 00:56
I am also seeing high cpu usage coming from this container.

**Comment by j0nnymoe** [comment] 2020-07-20 08:06
This happens when you have enhanced apps configured and they're communicating with the API's to get stat updates.

**Comment by dontevenblink** [comment] 2020-07-20 19:12
> This happens when you have enhanced apps configured and they're communicating with the API's to get stat updates.

After some testing, the Transmission API seems to be the worst offender. This doesn't seem like expected behavior, though - Heimdall communicating to the Transmission API seems to consume more CPI than Transmission itself. As stated above, when I have three APIs going (Transmission, Jellyfin, and Pi-hole), Heimdall consumes more CPU than any of those containers do.

**Comment by TheTinkerDad** [comment] 2021-05-07 12:13
One question though - why Heimdall keeps polling those APIs when it has like zero open client connections? I'd normally expect it to only poll those APIs when there's actually a user looking at the Heimdall UI. I doubt that many of us keep staring at the UI for hours, rather than just opening it, clicking on an app tile and going on our ways.

**Comment by Xitro01** [comment] 2021-11-16 12:08
Same issues here, looking at the dashboard vs not looking at the dashboard:
![dbd4fcef-474a-4688-863b-3fbc1abea014](https://user-images.githubusercontent.com/19844787/141982681-f46f34e0-6373-4abb-aa4d-35be97db7ee2.jpg)
![2a8988d2-93d5-46ef-bd04-852e2373d0d5](https://user-images.githubusercontent.com/19844787/141982684-d519e37d-8231-434b-b407-1ecbd26c09bb.jpg)

**Comment by tessierp** [comment] 2021-12-03 03:51
Same problem here..

Whenever APIs are being used and depending on how many are used on the dashboard, the CPU usage can jump above 50% usage when the dashboard is displayed. From my understanding this is happening because there is a constant pulling of information from all the APIs.

I have tried to find a global refresh setting or per app refresh setting but there doesn't seem to be any.

In order to help diminish the CPU usage, perhaps it would be a good idea to introduce a global refresh setting and one per application that overrides the global setting so that we can configure how often the data is being pulled in milliseconds or seconds.

**Comment by djcrawleravp** [comment] 2021-12-28 03:50
Same problem here using the latest docker image on RBPi Ubuntu

**Comment by Def3nder** [comment] 2022-01-05 13:44
same high CPU usage here:
![image](https://user-images.githubusercontent.com/33399267/148227072-f6127e66-42ac-4682-a162-692c07ab253f.png)

I have 5 "enhanced API" plates.

**Comment by djcrawleravp** [comment] 2022-01-06 21:26
Can someone recommend me the best previous tag?

**Comment by nedich** [comment] 2022-01-19 23:45
It seem little bit absurd that a page with bunch of links is taking so much cpu. I had to stop the container because my server was almost flying off with its fans spinning at their max due to the heimdall. I think in my case that the extra high activity was caused by heimdall + qbittorrent. It seems heimdal does not play nicely with the torrent clients.

@Def3nder can I ask something offtopic - what tool generated this cpu screen? looks cool.

**Comment by tessierp** [comment] 2022-01-20 01:16
> It seem little bit absurd that a page with bunch of links is taking so much cpu. I had to stop the container because my server was almost flying off with its fans spinning at their max due to the heimdall. I think in my case that the extra high activity was caused by heimdall + qbittorrent. It seems heimdal does not play nicely with the torrent clients.
> 
> @Def3nder can I ask something offtopic - what tool generated this cpu screen? looks cool.

Yeah this app needs optimization for sure..

As for your question about the graph, looking at the image I saw NETDATA and searched and found this : https://www.netdata.cloud

**Comment by aptalca** [comment] 2022-01-20 02:06
> It seem little bit absurd that a page with bunch of links is taking so much cpu

If you use it strictly as a `page with a bunch of links`, it will use hardly any cpu cycles. That means you have to disable all the `enhanced app` features like displaying stats inside the buttons. Those stat gathering operations are what use up cpu cycles.

**Comment by tessierp** [comment] 2022-01-20 02:16
Hi, that we know. But it shouldn't take as much CPU power as it does.

**Comment by aptalca** [comment] 2022-01-20 02:31
I just checked mine with `docker stats heimdall` and when heimdall is not open, the cpu usage is at a constant 0%.

When I open heimdall in a browser and keep it in the foreground, I see cpu usage fluctuating between 0-9%. If I switch to another tab in chrome, usage drops to 0% with spikes every so often. If I close the window, it drops to constant 0% again.

I have 18 buttons, 9 are enhanced.

I use heimdall as a browser homepage, so I don't have heimdall open for long periods of time. The 0-9% usage while open never bothered me (I didn't notice until I specifically checked).

For each enhanced button, it's running a php script that makes at least one (for some more than one) call to an external app's api and processes the results once every second, and updates the display. The more enhanced buttons, the more scripts, calls and processing.

**Comment by tessierp** [comment] 2022-01-20 02:52
While what you say is technically true, it should not  spike as high as it does. I have way less than that and yet usage spiked to above 47%. This causes my CPU to warm and my fans to turn at a higher regime. This is not the only other application I am running on this system and none of them take up that much CPU. Well there is PLEX but that is quite understandable. 

As a reference, I'm using ZABBIX which collects data from many systems, CPU temps, network bandwidth in and out, and more and it doesn't use that much CPU. 

The fact you do not have any issues doesn't mean there isn't any issues.

**Comment by aptalca** [comment] 2022-01-20 03:20
I didn't say there aren't any issues. I just shared my use case and results, which may point to an issue with a specific enhanced app that maybe you're using and I'm not.

Anyway, I'll bud out.

Good luck.

**Comment by tessierp** [comment] 2022-01-20 03:22
Thanks for sharing. Hopefully the devs find a solution.

**Comment by Def3nder** [comment] 2022-02-02 09:31
> > It seem little bit absurd that a page with bunch of links is taking so much cpu
> 
> If you use it strictly as a `page with a bunch of links`, it will use hardly any cpu cycles. That means you have to disable all the `enhanced app` features like displaying stats inside the buttons. Those stat gathering operations are what use up cpu cycles.

@aptalca yes, if you disable the `enhanced apps` then this peaks are gone, but then I could just use a static html-page and would not need heimdall. other containers like this (e.g. `DashMachine` ) do offer similar features and the use **below 0,1%** of the CPU - `Heimdall` goes up to the maximum available CPU.

**Comment by tessierp** [comment] 2022-02-02 14:04
Looks awesome.. Too bad DashMachine hasn't been supported in 2 years. I mean still good, but I guess it is not longer being worked on.

**Comment by j0nnymoe** [comment] 2022-02-02 14:07
Though I'm not the Dev of Heimdall, I doubt any fixes will be done for this as focus shifted over to a rewrite a number of months back: https://github.com/linuxserver/heimdalljs

It's worth checking out as to my knowledge, it's all there apart from the pre configured enhanced apps but you can manually do them yourself within the GUI.

**Comment by tessierp** [comment] 2022-02-02 14:34
Well, could be a good thing is they are doing a rewrite.. Thanks for the info!

**Comment by keriati** [comment] 2022-12-15 22:23
Should be resolved with: https://github.com/linuxserver/Heimdall/pull/1059

**Closed by keriati** 2022-12-15 22:23 UTC
