### ISSUE TITLE
Refresh items status only when browser window is active

### ISSUE THREAD

**Issue by qcgzxw** [linuxserver/Heimdall#828] opened 2022-04-11 08:53 UTC
I always forget to close the heimdall tab,So it just continue refresh in background.

We just want to see status of items when we at the heimdall tab, so it's unnecessary to refresh them in background.

**Comment by palmergw** [comment] 2022-04-12 16:44
I have this same issue, it actually has undesirable effects if your DNS server is not up to the task.
If I leave Heimdall open, I get ~7k requests in a 10-minute window, and it can break other applications' ability to successfully resolve. I'm using PiHole in a reasonable beefy VM for reference.

**Comment by mcondren** [comment] 2022-04-19 17:02
I just found this issue after I searched trying to figure out why my dns server was getting spammed by hundreds of dns queries per minute from heimdall.  It even seems to be sending dns queries for apps that I have completely deleted from the dashboard.

**Comment by qcgzxw** [comment] 2022-05-15 14:01
It seems that there was same issus and already fixed.
https://github.com/linuxserver/Heimdall/issues/330

@mcondren  @palmergw

**Comment by palmergw** [comment] 2022-05-15 20:25
I would like to suggest that this has re-broken then, @qcgzxw. If this was fixed in 2019, then it's definitely reproducible now, whether or not it's the same root cause. If a browser is left open with Heimdall in the foreground, it generates and unreal amount of DNS queries. Perhaps the OP does not simply mean active in the sense that the tab has focus, but active as in being used actively?

It has caused me enough trouble that I'd like to be able to reduce polling rate, or for the page to know I haven't interacted with it in 5 minutes and to slow down or stop polling.

**Comment by qcgzxw** [comment] 2022-05-16 12:34
> I would like to suggest that this has re-broken then, @qcgzxw. If this was fixed in 2019, then it's definitely reproducible now, whether or not it's the same root cause. If a browser is left open with Heimdall in the foreground, it generates and unreal amount of DNS queries. Perhaps the OP does not simply mean active in the sense that the tab has focus, but active as in being used actively?
> 
> It has caused me enough trouble that I'd like to be able to reduce polling rate, or for the page to know I haven't interacted with it in 5 minutes and to slow down or stop polling.


I don't know how to make it happen again.
It used to bother me because of the dns querying thing,but now this issue didn't occur.

**Comment by midwestsocrates** [comment] 2022-05-27 03:00
> > I would like to suggest that this has re-broken then, @qcgzxw. If this was fixed in 2019, then it's definitely reproducible now, whether or not it's the same root cause. If a browser is left open with Heimdall in the foreground, it generates and unreal amount of DNS queries. Perhaps the OP does not simply mean active in the sense that the tab has focus, but active as in being used actively?
> > It has caused me enough trouble that I'd like to be able to reduce polling rate, or for the page to know I haven't interacted with it in 5 minutes and to slow down or stop polling.
> 
> I don't know how to make it happen again. It used to bother me because of the dns querying thing,but now this issue didn't occur.

I don't know how to not make it happen. My internal DNS is getting hammered and Heimdall is pokey. What do you need to reopen this?

**Comment by martadinata666** [comment] 2022-05-27 03:31
So i cant make this happen, im using firefox, tested when changing tab making heimdall lose focus and dont querying anything. What browser you are using? Im thinking that the browser keep marking not focused tab as active or behaviour that mimick that.

**Comment by qcgzxw** [comment] 2022-05-28 17:37
> So i cant make this happen, im using firefox, tested when changing tab making heimdall lose focus and dont querying anything. What browser you are using? Im thinking that the browser keep marking not focused tab as active or behaviour that mimick that.


Now I can see the issue.This application is running background if there is an unclosed brower tab.
![image](https://user-images.githubusercontent.com/24518597/170836559-3f7525ae-9777-40b0-b6bc-590649bf3af1.png)

```shell
docker stats heimdall
```

**Comment by simensen** [comment] 2022-06-16 17:04
Can confirm this is happening to me as well. Could potentially be related to Portainer tile getting locked out due to rate limiting when anything else is already spinning.

I'm seeing 0% in `docker stats` when no tabs are open and steady alternating `0%` and `24%` CPU utilization with a tab open. When Portainer tile was enabled w/ API, and failing, it looked like it was causing the entire check loop to start over immediately. Now that I've disabled it, my Homebridge status check is happening once a second which seems to be why the `docker stats` output cycles between `0%` and `24%`.

I think I wasn't aware how frequently some of these tiles updated. They also look to be configured to check at different intervals independent of each other as my Homebridge tile appears to check far more frequently than my other tiles.

**Comment by keriati** [comment] 2022-12-13 16:09
This should be fixed with https://github.com/linuxserver/Heimdall/pull/1059

**Closed by keriati** 2022-12-13 16:09 UTC
