### ISSUE TITLE
Trying to add an entry with numeric value on the end of the URL will return validation error

### ISSUE THREAD

**Issue by arroadie** [linuxserver/Heimdall#317] opened 2019-01-22 16:50 UTC
**Describe the bug**
Url with number returns validation errors

**To Reproduce**
1. Go to /items
2. Click on "Add"
3. Fill all fields and use an url with a number eg: http://hydra2/
4. Validation error will be displayed "The url format is invalid."

**Expected behavior**
Values are accepted and the item is added to the dashboard

**Screenshots**
![screenshot](http://static.thiagocosta.io/screenshots/2019-01-22-08-30-29_1223x837.png)

**Desktop (please complete the following information):**
 - OS: Centos7
 - Browser [e.g. chrome, safari]: Firefox 
 - Version [e.g. 22]: 60.4.0esr (64-bit)

**Additional context**
Heimdall is running in a docker container in debian

**Comment by TheLux83** [comment] 2019-02-07 11:20
I can confirm the same behaviour from my site.
I'm trying to create an App for my internal site http://aserver01:8082/ and Heimdall says it's an invalid URL.
When I delete all numbers, it creates the App.

**Comment by TheLux83** [comment] 2019-05-06 08:32
Comming back after a few months to test Heimdall again. Unfortunately, the same error persists.
Is there anyone who can help me/us?

**Comment by j0nnymoe** [comment] 2019-05-06 08:34
If I remember correctly, it's due to the validator within laravel. It also has the same issue with `_` in urls aswell. @KodeStar will confirm this though.

**Comment by KodeStar** [comment] 2019-06-11 13:12
I've removed the valid url validation on master so it will be in the next version released (probably 2.0.1)

**Comment by KodeStar** [comment] 2019-06-19 10:00
Fixed in 2.2.1

**Closed by KodeStar** 2019-06-19 10:00 UTC
